import Head from "next/head";
import { NavBar } from "components/NavBar/NavBar";
import styles from "styles/Home.module.scss";
import PropertyCard from "components/PropertyCard/PropertyCard";
import { useState, useEffect } from "react";
import axios from "axios";

export default function Home() {
  const [properties, setProperties] = useState([]);

  useEffect(() => {
    axios
      .get("/properties")
      .then((res) => setProperties(res.data))
      .catch((e) => console.log(e));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Paseo360</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavBar />
        <div>
          <div></div>
          <div>
            {properties.length > 0 &&
              properties.map((property) => (
                <PropertyCard key={property._id} property={property} />
              ))}
          </div>
        </div>
      </main>
    </div>
  );
}
